### 1. Creating blank array, with predefined data, with pattern specific


In [ ]:
# Python program for
# Creation of Arrays

In [4]:
import numpy as np
empty_arr = np.empty([5,3])
print(empty_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
empty_arr = np.empty((3,3,3), dtype=np.int64)
print(empty_arr)
print(empty_arr)

[[[22518393277644867 32088589733920882 27303364805853281]
  [18296268629540980 31244147623002222 14355640430624878]
  [33214519704879196 29555241927835763 26740565175500914]]

 [[32651548273737777 25895921198891057 25896118771056748]
  [28429470870863987 27866439313522733 28429415035764843]
  [32933044727578739 25896217555763309 28147970123825266]]

 [[26740517931647087 28429445100798055 31244220637446258]
  [31525622596370546 33495715505700915 27303480770035817]
  [14636930723741805 28148017369448494                 0]]]
[[[22518393277644867 32088589733920882 27303364805853281]
  [18296268629540980 31244147623002222 14355640430624878]
  [33214519704879196 29555241927835763 26740565175500914]]

 [[32651548273737777 25895921198891057 25896118771056748]
  [28429470870863987 27866439313522733 28429415035764843]
  [32933044727578739 25896217555763309 28147970123825266]]

 [[26740517931647087 28429445100798055 31244220637446258]
  [31525622596370546 33495715505700915 27303480770035817]
  [1

In [29]:
string_arr = np.array([[2,2,2,2],[1,2,3,4]])
string_arr[0:2,0:2] = 1
print(string_arr)

[[1 1 2 2]
 [1 1 3 4]]


In [15]:
det = (["Virag","Patel","19IT114"])
print("Name : ", det[0])
print("Surname : ", det[1])
print("ID.No : ",det[2])

Name :  Virag
Surname :  Patel
ID.No :  19IT114


### 2. Slicing and Updating elements.

In [22]:

Details = np.array([["Viraj","Aayush","Shrey"],["19IT117","19IT127","19IT059"],["Patva","Desai","Makwana"]])

Details[0][1] = "Mrugrendra"

print (Details[0][0],"-> ",Details[:,0])
print (Details[0][1],"-> ",Details[:,1])
print (Details[0][2],"->",Details[:,2])



Viraj ->  ['Viraj' '19IT117' 'Patva']
Mrugren ->  ['Mrugren' '19IT127' 'Desai']
Shrey -> ['Shrey' '19IT059' 'Makwana']


### 3. Shape manipulations

In [37]:
identity = np.eye(5,5)
print("Iden",identity)
a = np.reshape(identity[0:3,0:3],(9,1))
print("A = ",a)

Iden [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
A =  [[1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]]


### 4. Looping over Arrays


In [42]:
a = range (5)
for i in a:
    print(i)
print(a)

0
1
2
3
4
range(0, 5)
